### ISSUE TITLE
Implement 2FA

### ISSUE THREAD

**Issue by ashtrindade** [LunaCrew/accounts-core#34]
> **Given** that user can be created
> **When** create the user
> **Then** should setup 2FA

## To-do

- [ ] setup 2FA on user creation
- [ ] request 2FA on user login
- [ ] request 2FA on user delete

### Acceptance criteria

- [ ] unit tests

**Depends on**: #14

**Comment by ashtrindade** [comment]
Verification will be made on app.
