### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by ashtrindade** [LunaCrew/accounts-core#49]
> **Given** that the user creates an account
> **Then** should send a verification token to user email

> **Given** the user sends back the verification token
> **Then** should validate the token
> **And** if the token is valid
> **Then** should validate the user account
> **And** if the token is invalid
> **Then** should prompt the user to send another token

## Todo

- [ ] Add `emailValidated: boolean` to userSchema
- [ ] Send verification email
- [ ] Update `emailValidated` when the token is valid
